theme: jekyll-theme-leap-day
title: Multitech System Technical Documentation
description: Collection of articles for working with Multitech devices in LoRaWAN networks.
favicon: favicon.ico
plugins:
  - jekyll-feed
  - jekyll-seo-tag

github:
  is_project_page: false